export interface IdriverTripResponse {
   id :  string ,
   drvNam :  string ,
   prflImg : string,
   groupName : string ,
   tripTypeId :  string ,
   tripTypeAr :  string ,
   tripTypeEn :  string ,
   tripstatNamAr :   string ,
  tripstatNamEn: string,
  typeDate: Date,
   typestats : string,
   tripStatus :  string,
   tripDriverIncome : number,
}
