export interface IclientTripResponse {
  id:string,
  triptaId: string,
  CarClr: string,
  CarMdl: string,
  carNum: string,
  drvCode: string ,
  drvPhone: string,
  drvLicenUrl: string ,
  drvNam: string ,
  drvCarLicenUrl: string,
  prflImg: string,
  trpTyp: string,
  trpDurtn: string,
  trpStats: string,
  trpStrtDat: Date,
  trpEndDat: Date,
  trpPassNo: number,
  trpNts: string,
  trpStrtTme: Date,
  trpEndTme: Date,
  trpLat: number,
  trpLong: number,
  trpFrmAdrs: string
  trpToLat: string,
  trpToLong: string,
  trpToAdrs: string,
  isFullyReservied: boolean,
  isGoingAndBack: boolean,
  scolNamAr: string,
  scolNamEn: string
}
